# ruff: noqa: F403
from .base import *
from .campo_formulario import *
from .criterio_avaliacao import *
from .area_conhecimento import *
from .arquivo import *
from .espaco import *
from .evento import *
from .cronograma import *
from .local import *
from .modalidade import *
from .resposta import *
from .sessao import *
