# ruff: noqa: F403
from .area_conhecimento_escolha import *
from .nivel_ensino import *
from .setor import *
from .status_aprovacao import *
from .status_atracao import *
from .status_evento import *
from .status_inscricao import *
from .tipo_campo import *
from .tipo_etapa import *
